# Generated by Django 5.2.1 on 2025-05-16 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hexagrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True)),
                ('nombre_chino', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('significado', models.TextField()),
                ('recomendacion', models.TextField()),
                ('monedas', models.JSONField(help_text="Lista de 6 valores: 'yin' o 'yang'")),
            ],
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='hexagrama_nombre',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='hexagrama_nombre_chino',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='hexagrama_numero',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='recomendacion',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='significado',
        ),
        migrations.AddField(
            model_name='consulta',
            name='hexagrama',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oraculo.hexagrama'),
            preserve_default=False,
        ),
    ]
