# Generated by Django 5.2.1 on 2025-05-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0002_hexagrama_remove_consulta_hexagrama_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hexagrama',
            name='numero',
        ),
        migrations.AlterField(
            model_name='hexagrama',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
