# Generated by Django 5.2.1 on 2025-05-16 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0003_remove_hexagrama_numero_alter_hexagrama_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hexagrama',
            name='numero',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='hexagrama',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='oraculo.hexagrama'),
        ),
        migrations.AlterField(
            model_name='hexagrama',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
