# Generated by Django 5.2.1 on 2025-05-16 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0004_hexagrama_numero_alter_consulta_hexagrama_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='hexagrama',
        ),
    ]
