# Generated by Django 5.2.1 on 2025-05-16 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0005_remove_consulta_hexagrama'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='hexagrama',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='oraculo.hexagrama'),
        ),
    ]
