# Generated by Django 5.2.1 on 2025-05-22 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0006_consulta_hexagrama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='hexagrama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oraculo.hexagrama'),
        ),
    ]
